name: Working Dirs and Shells
on: [push]
jobs: 
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Displaying Working Directory & List Files
              run: | 
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WROKSPACE
    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Displaying Working Directory & List Files
              run: | 
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WROKSPACE

           